[package]
name = "mpsc"
version = "0.1.0"
edition = "2021"

[features]
default = []
simd = []  # Enable SIMD optimizations (requires nightly)

[dependencies]
arrayvec = "0.7.6"
crossbeam-utils = "0.8.21"
num_cpus = "1.16.0"
parking_lot = "0.12.3"
ringbuf = "0.4.8"
triomphe = "0.1.14"
